### ISSUE TITLE
Error: r is not a constructor

### ISSUE THREAD

**Issue by CNMathon** [nihalgonsalves/node-typescript-eslint-template#322]
Hi, I tried to use this template. But when I lint with prettier-eslint, it always throws an error like the one below.

- Environment Info
  - Development Environment
    - VSCode 👉 v1.63.2
      - ESLint 👉 v2.2.2
      - Prettier ESLint 👉  v3.1.0
  - package
    - @typescript-eslint/eslint-plugin 👉 v5.8.1
    - @typescript-eslint/parser 👉 v5.8.1
    - eslint 👉 v7.14.0
    - prettier 👉 v2.3.2
    - prettier-eslint 👉 v12.0.0
    - typescript 👉 v4.5.4

![image](https://user-images.githubusercontent.com/44454223/147896114-3d484028-88e3-4a39-9ee7-82f1be9c520c.png)

**Comment by nihalgonsalves** [comment]
Hi @CNMathon, this doesn't seem to be an issue with this template but with the extension you're using - their [README](https://github.com/idahogurl/vs-code-prettier-eslint) specifies that it supports prettier v1 and eslint v6, so it's rather outdated. It looks like there is a beta version you could try, but even that only says it supports eslint v7, not v8.

I would personally suggest uninstalling that extension and using the usual prettier and eslint vscode extensions. They work fine for me and do not need additional configuration since the included eslint config disables all formatting rules and lets prettier handle the formatting.

This template also has auto fix on save pre-configured for both, and recommends them on first open (look in the extensions tab if you dismissed it).

Hope that helps! Closing since this isn't an issue with the template.
